In [1]:
import sklearn as sk
from sklearn import cluster
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import pairwise_distances_argmin
from sklearn.metrics.pairwise import pairwise_distances
%matplotlib inline

In [2]:
predata = pd.read_table('Pima-prediction-set.txt', header=None)
data = pd.read_table('Pima-training-set.txt', header=None)

In [3]:
prey = predata[8].values
preX = predata.ix[:, 0:7].values

In [4]:
y = data[8].values
X_O = data.ix[:, 0:7].values

In [ ]:
help(sk.cluster.KMeans)

In [ ]:
fea = [5,1,6,7,4,0,3,2] # fisher
for i in range(1, len(fea)+1):
    max_s = 0
    max_center = []
    clf = sk.cluster.KMeans(n_clusters = 2, n_init = 130, n_jobs = 5)
    clf.fit(X_O[:,fea[:i]])
    
    tlabel = pairwise_distances_argmin(X_O[:,fea[:i]], clf.cluster_centers_)
#     tlabel = clf.predict(X_O[:,fea[:i]])
    tlabel[tlabel==0] = 1 
    tlabel[tlabel!=0] = 2 
    trainacc = sum(tlabel == y) / len(y)
    
    plabel = pairwise_distances_argmin(preX[:,fea[:i]], clf.cluster_centers_)
#     plabel = clf.predict(preX[:,fea[:i]])
    plabel[plabel==0] = 1 
    plabel[plabel!=0] = 2 
    preacc = sum(plabel == prey) / len(prey)
    
    print("------------------------------------")
    print('fea: ', fea[:i])
    print(clf.cluster_centers_)
    print('train:', max(trainacc, 1-trainacc))
    print('pre:  ', max(preacc, 1-preacc))

In [17]:
fea = [5,1,6,7,4,0,3,2] # fisher
for i in range(1, len(fea)+1):
    max_s = 0
    max_center = []
    clf = sk.cluster.KMeans(n_clusters = 2, n_init = 130, algorithm='elkan', n_jobs = 5)
    clf.fit(X_O[:,fea[:i]])
    
    tlabel = clf.predict(X_O[:,fea[:i]]) 
    tlabel[tlabel==0] = 2
    trainacc = sum(tlabel == y) / len(y)
    
    plabel = clf.predict(preX[:,fea[:i]])
    plabel[plabel==0] = 2 
    preacc = sum(plabel == prey) / len(prey)
    
    print("------------------------------------")
    print('fea: ', fea[:i])
    print(clf.cluster_centers_)
    print('train:', max(trainacc, 1-trainacc))
    print('pre:  ', max(preacc, 1-preacc))

------------------------------------
fea:  [5]
[[ 0.56097863]
 [ 0.38736054]]
train: 0.626644736842
pre:   0.5625
------------------------------------
fea:  [5, 1]
[[ 0.44663414  0.5126274 ]
 [ 0.5294218   0.77292855]]
train: 0.740131578947
pre:   0.7375
------------------------------------
fea:  [5, 1, 6]
[[ 0.53308758  0.76053512  0.22317857]
 [ 0.44247391  0.51389843  0.13312731]]
train: 0.761513157895
pre:   0.7375
------------------------------------
fea:  [5, 1, 6, 7]
[[ 0.49481358  0.70231758  0.18237801  0.44378111]
 [ 0.46738704  0.55901125  0.15925088  0.09418513]]
train: 0.697368421053
pre:   0.7
------------------------------------
fea:  [5, 1, 6, 7, 4]
[[ 0.46738704  0.55901125  0.15925088  0.09418513  0.09297692]
 [ 0.49481358  0.70231758  0.18237801  0.44378111  0.09286899]]
train: 0.697368421053
pre:   0.7
------------------------------------
fea:  [5, 1, 6, 7, 4, 0]
[[ 0.47265258  0.58056867  0.16158619  0.09975433  0.09968286  0.11981517]
 [ 0.48415152  0.65866647  0.

In [20]:
fea = np.array([5,1,6,7,4,0,3,2]) # fisher
clf = sk.cluster.KMeans(n_clusters = 2, n_jobs = 5)
clf.fit(X_O[:,fea[[4,0]]])
plabel = clf.predict(preX[:,fea[[4,0]]])
plabel += 1 
score = sum(plabel == prey) / len(prey)
print('  pre:  ', max(score, 1-score))

  pre:   0.68125


In [29]:
clf.score(preX[:,fea[[4,0]]], y=prey-1)

-4.2106221060491444

In [ ]:
# prelabel2 = clf.predict(preX)
prelabel2 += 1
acc = sum(prelabel2 == prey) / len(prey)
acc

In [5]:
cen = np.array([[ 0.44663414, 0.5126274 ], [ 0.5294218, 0.77292855]])

In [11]:
cen

array([[ 0.44663414,  0.5126274 ],
       [ 0.5294218 ,  0.77292855]])

In [15]:
preX[0,[5, 1]]

array([ 0.460507,  0.532663])

In [6]:
D = pairwise_distances(preX[:, [5,1]], cen)

In [10]:
D

array([[ 0.02436968,  0.24995356],
       [ 0.20418009,  0.07544258],
       [ 0.11527626,  0.19020722],
       [ 0.14924033,  0.21790934],
       [ 0.12596987,  0.38269738],
       [ 0.15726844,  0.28039894],
       [ 0.45380192,  0.55917289],
       [ 0.22984814,  0.27670156],
       [ 0.13114677,  0.15491392],
       [ 0.18705663,  0.35147092],
       [ 0.24194172,  0.30085316],
       [ 0.17395192,  0.22046151],
       [ 0.1300705 ,  0.32230286],
       [ 0.26143186,  0.09276457],
       [ 0.07581092,  0.27607283],
       [ 0.23245782,  0.39428702],
       [ 0.45067783,  0.56596225],
       [ 0.09961867,  0.35350323],
       [ 0.02716473,  0.24875799],
       [ 0.20522181,  0.32735745],
       [ 0.041379  ,  0.24833208],
       [ 0.09727268,  0.18620219],
       [ 0.08551363,  0.35511581],
       [ 0.1056104 ,  0.37471701],
       [ 0.03565491,  0.28132795],
       [ 0.12885213,  0.14705002],
       [ 0.10397865,  0.33946966],
       [ 0.25123735,  0.02275864],
       [ 0.05730915,

In [7]:
label = D[:,0] - D[:,1]
tmp = label>=0
tmp

array([False,  True, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False,  True, False,  True,  True,  True,
       False, False, False, False, False,  True, False, False, False,
        True, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False,  True, False, False,  True, False, False,  True,  True,
       False, False, False, False,  True, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
        True,  True, False,  True, False, False,  True,  True, False,
        True, False, False,  True, False, False, False,  True,  True,
        True,  True, False, False, False,  True,  True,  True, False,
        True, False,  True,  True,  True, False, False,  True,  True,
       False, False,

In [8]:
label[tmp] = 1
label[~tmp] = 2
label

array([ 2.,  1.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        1.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  1.,  2.,  2.,  2.,  1.,  2.,  1.,  1.,  1.,  2.,  2.,  2.,
        2.,  2.,  1.,  2.,  2.,  2.,  1.,  2.,  1.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  1.,  2.,  1.,
        2.,  2.,  1.,  2.,  2.,  1.,  1.,  2.,  2.,  2.,  2.,  1.,  2.,
        2.,  2.,  2.,  2.,  1.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  1.,
        1.,  2.,  1.,  2.,  2.,  1.,  1.,  2.,  1.,  2.,  2.,  1.,  2.,
        2.,  2.,  1.,  1.,  1.,  1.,  2.,  2.,  2.,  1.,  1.,  1.,  2.,
        1.,  2.,  1.,  1.,  1.,  2.,  2.,  1.,  1.,  2.,  2.,  1.,  2.,
        2.,  1.,  1.,  1.,  2.,  2.,  1.,  1.,  1.,  1.,  2.,  1.,  1.,
        1.,  1.,  1.,  2.,  1.,  1.,  2.,  1.,  1.,  1.,  1.,  1.,  1.,
        2.,  1.,  1.,  1.])

In [23]:
help(clf.score)

Help on method score in module sklearn.cluster.k_means_:

score(X, y=None) method of sklearn.cluster.k_means_.KMeans instance
    Opposite of the value of X on the K-means objective.
    
    Parameters
    ----------
    X : {array-like, sparse matrix}, shape = [n_samples, n_features]
        New data.
    
    Returns
    -------
    score : float
        Opposite of the value of X on the K-means objective.

